name: Bug report
description: Report a bug to be fixed
labels: [bug]
assignees: [tantalun-moon]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe your bug and any related information here:"
    validations:
      required: true

  - type: textarea
    id: terminal
    attributes:
      label: "Copy your command prompt error logs here (if any):"
      render: bash
    validations:
      required: false
