name: Change request
description: Request a change to be made
labels: [change, to-do]
assignees: [tantalun-moon]
body:
  - type: textarea
    attributes:
      label: "Describe your desired change:"
    validations:
      required: true
