name: Feature request
description: Request a feature to be added
labels: [feature, to-do]
assignees: [tantalun-moon]
body:
  - type: textarea
    attributes:
      label: "Describe your desired feature:"
    validations:
      required: true
