name: Edit request
description: Request an edit to be done
labels: [edit, to-do]
assignees: [tantalun-moon]
body:
  - type: textarea
    attributes:
      label: "Describe your desired edit:"
    validations:
      required: true
